name: RayTraceAntiXray
main: com.vanillage.raytraceantixray.RayTraceAntiXray
version: 1.5.0
api-version: 1.17
description: Paper plugin for server-side async multithreaded ray tracing to hide ores that are exposed to air using Paper Anti-Xray engine-mode 1.
load: STARTUP
depend: [ProtocolLib]
